//! USB gadget support.
//!
//! Raspberry Pi 5 exposes peripheral mode on the USB-C connector, but it has
//! no OTG_ID line, so `dtoverlay=dwc2,dr_mode=peripheral` is required in
//! `config.txt` (emitted by [`crate::config_txt`]). The gadget itself is
//! composed at runtime through configfs, which is what the script below does.
//!
//! Note that the USB-C connector is also the power input on this board. When
//! the gadget link is in use, power the board through the GPIO header.

use std::fmt::Write as _;

use rpi_provision_spec::model::{GadgetFunction, UsbGadget};

use crate::PayloadFile;

pub const SCRIPT_PATH: &str = "/usr/local/sbin/rpi-provision-gadget";
pub const UNIT_NAME: &str = "rpi-provision-gadget.service";

/// The configfs composition script.
pub fn script(gadget: &UsbGadget) -> PayloadFile {
    let function = gadget.function.configfs_name();
    let instance = &gadget.interface;
    let mut out = String::new();

    let _ = writeln!(out, "#!/bin/sh");
    let _ = writeln!(out, "# Generated by {}. Do not edit.", crate::GENERATOR);
    let _ = writeln!(out, "#");
    let _ = writeln!(out, "# Compose a USB {} gadget through configfs.", gadget.function.as_str());
    let _ = writeln!(out, "set -eu");
    let _ = writeln!(out);
    let _ = writeln!(out, "GADGET_NAME=\"rpiprov\"");
    let _ = writeln!(out, "CONFIGFS=\"/sys/kernel/config/usb_gadget\"");
    let _ = writeln!(out, "G=\"$CONFIGFS/$GADGET_NAME\"");
    let _ = writeln!(out, "FUNC=\"{function}.{instance}\"");
    let _ = writeln!(out, "ID_VENDOR=\"0x{:04x}\"", gadget.vendor_id);
    let _ = writeln!(out, "ID_PRODUCT=\"0x{:04x}\"", gadget.product_id);
    let _ = writeln!(out, "MANUFACTURER=\"{}\"", gadget.manufacturer);
    let _ = writeln!(out, "PRODUCT=\"{}\"", gadget.product);
    let _ = writeln!(out, "SERIAL=\"{}\"", gadget.serial);
    let _ = writeln!(out, "DEV_ADDR=\"{}\"", gadget.device_mac);
    let _ = writeln!(out, "HOST_ADDR=\"{}\"", gadget.host_mac);
    let _ = writeln!(out);
    let _ = writeln!(out, "die() {{ printf 'rpi-provision-gadget: %s\\n' \"$*\" >&2; exit 1; }}");
    let _ = writeln!(out);
    let _ = writeln!(out, "up() {{");
    let _ = writeln!(out, "    modprobe libcomposite || die \"cannot load libcomposite\"");
    let _ =
        writeln!(out, "    [ -d \"$CONFIGFS\" ] || die \"configfs is not mounted at $CONFIGFS\"");
    let _ = writeln!(out, "    if [ -d \"$G\" ]; then");
    let _ = writeln!(out, "        return 0");
    let _ = writeln!(out, "    fi");
    let _ = writeln!(out, "    mkdir -p \"$G\"");
    let _ = writeln!(out, "    printf '%s' \"$ID_VENDOR\"  > \"$G/idVendor\"");
    let _ = writeln!(out, "    printf '%s' \"$ID_PRODUCT\" > \"$G/idProduct\"");
    let _ = writeln!(out, "    printf '%s' '0x0200'       > \"$G/bcdUSB\"");
    let _ = writeln!(out, "    printf '%s' '0x0100'       > \"$G/bcdDevice\"");
    let _ = writeln!(out, "    mkdir -p \"$G/strings/0x409\"");
    let _ = writeln!(out, "    printf '%s' \"$MANUFACTURER\" > \"$G/strings/0x409/manufacturer\"");
    let _ = writeln!(out, "    printf '%s' \"$PRODUCT\"      > \"$G/strings/0x409/product\"");
    let _ = writeln!(out, "    printf '%s' \"$SERIAL\"       > \"$G/strings/0x409/serialnumber\"");
    let _ = writeln!(out, "    mkdir -p \"$G/configs/c.1/strings/0x409\"");
    let _ = writeln!(
        out,
        "    printf '%s' \"$PRODUCT\" > \"$G/configs/c.1/strings/0x409/configuration\""
    );
    let _ = writeln!(out, "    printf '%s' '250'      > \"$G/configs/c.1/MaxPower\"");
    let _ = writeln!(out, "    mkdir -p \"$G/functions/$FUNC\"");
    let _ = writeln!(out, "    if [ -e \"$G/functions/$FUNC/dev_addr\" ]; then");
    let _ = writeln!(out, "        printf '%s' \"$DEV_ADDR\"  > \"$G/functions/$FUNC/dev_addr\"");
    let _ = writeln!(out, "        printf '%s' \"$HOST_ADDR\" > \"$G/functions/$FUNC/host_addr\"");
    let _ = writeln!(out, "    fi");

    if gadget.function == GadgetFunction::Rndis {
        // Windows hosts need Microsoft OS descriptors to bind the RNDIS driver.
        let _ = writeln!(out, "    printf '%s' '1'        > \"$G/os_desc/use\"");
        let _ = writeln!(out, "    printf '%s' '0xcd'     > \"$G/os_desc/b_vendor_code\"");
        let _ = writeln!(out, "    printf '%s' 'MSFT100'  > \"$G/os_desc/qw_sign\"");
        let _ = writeln!(
            out,
            "    printf '%s' 'RNDIS'    > \"$G/functions/$FUNC/os_desc/interface.rndis/compatible_id\""
        );
        let _ = writeln!(
            out,
            "    printf '%s' '5162001'  > \"$G/functions/$FUNC/os_desc/interface.rndis/sub_compatible_id\""
        );
    }

    let _ = writeln!(out, "    ln -sf \"$G/functions/$FUNC\" \"$G/configs/c.1/\"");
    if gadget.function == GadgetFunction::Rndis {
        let _ = writeln!(out, "    ln -sf \"$G/configs/c.1\" \"$G/os_desc/\"");
    }
    // Globbing rather than parsing ls (SC2012); the first UDC is the one.
    let _ = writeln!(out, "    udc=''");
    let _ = writeln!(out, "    for candidate in /sys/class/udc/*; do");
    let _ = writeln!(out, "        [ -e \"$candidate\" ] || continue");
    let _ = writeln!(out, "        udc=\"${{candidate##*/}}\"");
    let _ = writeln!(out, "        break");
    let _ = writeln!(out, "    done");
    let _ = writeln!(
        out,
        "    [ -n \"$udc\" ] || die \"no UDC found; check dtoverlay=dwc2,dr_mode=peripheral in config.txt\""
    );
    let _ = writeln!(out, "    printf '%s' \"$udc\" > \"$G/UDC\"");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "down() {{");
    let _ = writeln!(out, "    [ -d \"$G\" ] || return 0");
    let _ = writeln!(out, "    printf '' > \"$G/UDC\" 2>/dev/null || true");
    if gadget.function == GadgetFunction::Rndis {
        let _ = writeln!(out, "    rm -f \"$G/os_desc/c.1\"");
    }
    let _ = writeln!(out, "    rm -f \"$G/configs/c.1/$FUNC\"");
    let _ = writeln!(out, "    rmdir \"$G/configs/c.1/strings/0x409\" 2>/dev/null || true");
    let _ = writeln!(out, "    rmdir \"$G/configs/c.1\"             2>/dev/null || true");
    let _ = writeln!(out, "    rmdir \"$G/functions/$FUNC\"         2>/dev/null || true");
    let _ = writeln!(out, "    rmdir \"$G/strings/0x409\"           2>/dev/null || true");
    let _ = writeln!(out, "    rmdir \"$G\"                         2>/dev/null || true");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "case \"${{1:-up}}\" in");
    let _ = writeln!(out, "    up)   up ;;");
    let _ = writeln!(out, "    down) down ;;");
    let _ = writeln!(out, "    *)    die \"usage: $0 [up|down]\" ;;");
    let _ = writeln!(out, "esac");

    PayloadFile::generated("usr/local/sbin/rpi-provision-gadget", SCRIPT_PATH, "0755", out)
}

/// The unit that brings the gadget up before NetworkManager looks for links.
pub fn unit(gadget: &UsbGadget) -> PayloadFile {
    let contents = format!(
        "# Generated by {generator}. Do not edit.\n\
         [Unit]\n\
         Description=rpi-provision USB {function} gadget\n\
         After=sys-kernel-config.mount systemd-modules-load.service\n\
         Requires=sys-kernel-config.mount\n\
         Before=network-pre.target\n\
         Wants=network-pre.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         RemainAfterExit=yes\n\
         ExecStart={script} up\n\
         ExecStop={script} down\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        generator = crate::GENERATOR,
        function = gadget.function.as_str(),
        script = SCRIPT_PATH,
    );
    PayloadFile::generated(
        format!("etc/systemd/system/{UNIT_NAME}"),
        format!("/etc/systemd/system/{UNIT_NAME}"),
        "0644",
        contents,
    )
}

/// Load `libcomposite` early so the unit does not race the module loader.
pub fn modules_load() -> PayloadFile {
    PayloadFile::generated(
        "etc/modules-load.d/rpi-provision-gadget.conf",
        "/etc/modules-load.d/rpi-provision-gadget.conf",
        "0644",
        format!("# Generated by {}. Do not edit.\nlibcomposite\n", crate::GENERATOR),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use rpi_provision_spec::net::Ipv4Cidr;
    use rpi_provision_spec::MacAddr;

    fn gadget(function: GadgetFunction) -> UsbGadget {
        UsbGadget {
            function,
            interface: "usb0".into(),
            address: Ipv4Cidr::parse("10.55.0.1/24").unwrap(),
            peer_address: None,
            device_mac: MacAddr::parse("02:11:22:33:44:55").unwrap(),
            host_mac: MacAddr::parse("02:11:22:33:44:56").unwrap(),
            vendor_id: 0x1d6b,
            product_id: 0x0104,
            manufacturer: "Raspberry Pi".into(),
            product: "rpi-provision USB gadget".into(),
            serial: "dev-pi-01".into(),
        }
    }

    #[test]
    fn ecm_script_has_expected_shape() {
        let file = script(&gadget(GadgetFunction::Ecm));
        assert_eq!(file.mode, "0755");
        assert!(file.text().starts_with("#!/bin/sh\n"));
        assert!(file.text().contains("set -eu"));
        assert!(file.text().contains("FUNC=\"ecm.usb0\""));
        assert!(file.text().contains("ID_VENDOR=\"0x1d6b\""));
        assert!(file.text().contains("DEV_ADDR=\"02:11:22:33:44:55\""));
        assert!(file.text().contains("HOST_ADDR=\"02:11:22:33:44:56\""));
        assert!(file.text().contains("/sys/class/udc"));
        assert!(!file.text().contains("os_desc"), "ECM needs no Microsoft descriptors");
    }

    #[test]
    fn rndis_script_adds_microsoft_descriptors() {
        let file = script(&gadget(GadgetFunction::Rndis));
        assert!(file.text().contains("FUNC=\"rndis.usb0\""));
        assert!(file.text().contains("qw_sign"));
        assert!(file.text().contains("compatible_id"));
        assert!(file.text().contains("ln -sf \"$G/configs/c.1\" \"$G/os_desc/\""));
    }

    #[test]
    fn ncm_script_selects_the_right_function() {
        let file = script(&gadget(GadgetFunction::Ncm));
        assert!(file.text().contains("FUNC=\"ncm.usb0\""));
    }

    #[test]
    fn unit_orders_before_networking() {
        let file = unit(&gadget(GadgetFunction::Ecm));
        assert!(file.text().contains("Before=network-pre.target"));
        assert!(file.text().contains("Requires=sys-kernel-config.mount"));
        assert!(file.text().contains(&format!("ExecStart={SCRIPT_PATH} up")));
        assert!(file.text().contains("WantedBy=multi-user.target"));
        assert_eq!(file.destination, "/etc/systemd/system/rpi-provision-gadget.service");
    }

    #[test]
    fn modules_load_requests_libcomposite() {
        let file = modules_load();
        assert!(file.text().contains("libcomposite"));
        assert_eq!(file.mode, "0644");
    }
}
