//! NetworkManager keyfile generation.
//!
//! Raspberry Pi OS has used NetworkManager since Bookworm, so connections are
//! expressed as keyfiles under `/etc/NetworkManager/system-connections/`.
//! They must be owned by root with mode 0600 or NetworkManager refuses to
//! load them.

use std::fmt::Write as _;

use rpi_provision_spec::model::{
    EthernetConnection, IpConfig, IpMethod, UsbGadget, WifiConnection, WifiSecurity,
};
use rpi_provision_spec::net::derive_uuid;

use crate::PayloadFile;

const DIRECTORY: &str = "/etc/NetworkManager/system-connections";

fn keyfile_path(id: &str) -> (String, String) {
    (
        format!("etc/NetworkManager/system-connections/{id}.nmconnection"),
        format!("{DIRECTORY}/{id}.nmconnection"),
    )
}

fn header(
    out: &mut String,
    id: &str,
    kind: &str,
    interface: &str,
    autoconnect: bool,
    priority: i64,
) {
    let _ = writeln!(out, "# Generated by {}. Do not edit.", crate::GENERATOR);
    let _ = writeln!(out, "[connection]");
    let _ = writeln!(out, "id={id}");
    let _ =
        writeln!(out, "uuid={}", derive_uuid(format!("rpi-provision/connection/{id}").as_bytes()));
    let _ = writeln!(out, "type={kind}");
    let _ = writeln!(out, "interface-name={interface}");
    let _ = writeln!(out, "autoconnect={}", if autoconnect { "true" } else { "false" });
    let _ = writeln!(out, "autoconnect-priority={priority}");
}

fn ip_sections(out: &mut String, ip: &IpConfig, may_fail: bool) {
    let _ = writeln!(out);
    let _ = writeln!(out, "[ipv4]");
    let _ = writeln!(out, "method={}", ip.method.as_nm());
    if let Some(address) = ip.address {
        match ip.gateway {
            Some(gateway) => {
                let _ = writeln!(out, "address1={address},{gateway}");
            }
            None => {
                let _ = writeln!(out, "address1={address}");
            }
        }
    }
    if !ip.dns.is_empty() {
        let rendered: Vec<String> = ip.dns.iter().map(|address| address.to_string()).collect();
        let _ = writeln!(out, "dns={};", rendered.join(";"));
    }
    if ip.ignore_auto_dns {
        let _ = writeln!(out, "ignore-auto-dns=true");
    }
    let _ = writeln!(out, "may-fail={}", if may_fail { "true" } else { "false" });

    let _ = writeln!(out);
    let _ = writeln!(out, "[ipv6]");
    let _ = writeln!(out, "addr-gen-mode=default");
    let _ = writeln!(out, "method={}", ip.ipv6.as_nm());
}

/// A wired connection profile.
pub fn ethernet_profile(connection: &EthernetConnection) -> PayloadFile {
    let mut out = String::new();
    header(
        &mut out,
        &connection.id,
        "ethernet",
        &connection.interface,
        connection.autoconnect,
        connection.autoconnect_priority,
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "[ethernet]");
    if let Some(mac) = connection.mac {
        let _ = writeln!(out, "cloned-mac-address={mac}");
    }
    // A statically addressed wired link is usually the one an operator relies
    // on, so hold up `network-online.target` until it is configured.
    ip_sections(&mut out, &connection.ip, connection.ip.method != IpMethod::Manual);

    let (source, destination) = keyfile_path(&connection.id);
    PayloadFile { source, destination, mode: "0600", contents: out, sensitive: false }
}

/// A wireless connection profile. The pre-shared key makes it sensitive.
pub fn wifi_profile(connection: &WifiConnection) -> PayloadFile {
    let mut out = String::new();
    header(
        &mut out,
        &connection.id,
        "wifi",
        &connection.interface,
        connection.autoconnect,
        connection.autoconnect_priority,
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "[wifi]");
    let _ = writeln!(out, "mode=infrastructure");
    let _ = writeln!(out, "ssid={}", connection.ssid);
    if connection.hidden {
        let _ = writeln!(out, "hidden=true");
    }

    if let Some(psk) = &connection.psk {
        let _ = writeln!(out);
        let _ = writeln!(out, "[wifi-security]");
        let _ = writeln!(
            out,
            "key-mgmt={}",
            match connection.security {
                WifiSecurity::WpaPsk => "wpa-psk",
                WifiSecurity::Sae => "sae",
                WifiSecurity::Open => unreachable!("an open network carries no key"),
            }
        );
        let _ = writeln!(out, "psk={psk}");
        let _ = writeln!(out, "psk-flags=0");
    }

    ip_sections(&mut out, &connection.ip, true);

    let (source, destination) = keyfile_path(&connection.id);
    PayloadFile {
        source,
        destination,
        mode: "0600",
        contents: out,
        sensitive: connection.psk.is_some(),
    }
}

/// The static address on the USB gadget link.
///
/// `may-fail` is true and no gateway is configured: the gadget link is a
/// side channel and must never become the default route or delay boot when
/// the cable is unplugged.
pub fn gadget_profile(gadget: &UsbGadget) -> PayloadFile {
    let id = format!("{}-gadget", gadget.interface);
    let mut out = String::new();
    header(&mut out, &id, "ethernet", &gadget.interface, true, 200);
    let _ = writeln!(out);
    let _ = writeln!(out, "[ethernet]");

    let _ = writeln!(out);
    let _ = writeln!(out, "[ipv4]");
    let _ = writeln!(out, "method=manual");
    let _ = writeln!(out, "address1={}", gadget.address);
    let _ = writeln!(out, "never-default=true");
    let _ = writeln!(out, "may-fail=true");

    let _ = writeln!(out);
    let _ = writeln!(out, "[ipv6]");
    let _ = writeln!(out, "addr-gen-mode=default");
    let _ = writeln!(out, "method=disabled");

    let (source, destination) = keyfile_path(&id);
    PayloadFile { source, destination, mode: "0600", contents: out, sensitive: false }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rpi_provision_spec::net::Ipv4Cidr;
    use rpi_provision_spec::MacAddr;
    use std::net::Ipv4Addr;

    fn static_ethernet() -> EthernetConnection {
        EthernetConnection {
            id: "eth0-static".into(),
            interface: "eth0".into(),
            ip: IpConfig {
                method: IpMethod::Manual,
                address: Some(Ipv4Cidr::parse("192.168.1.50/24").unwrap()),
                gateway: Some(Ipv4Addr::new(192, 168, 1, 1)),
                dns: vec![Ipv4Addr::new(192, 168, 1, 1), Ipv4Addr::new(1, 1, 1, 1)],
                ignore_auto_dns: false,
                ipv6: IpMethod::Disabled,
            },
            autoconnect: true,
            autoconnect_priority: 100,
            mac: None,
        }
    }

    #[test]
    fn renders_static_ethernet() {
        let file = ethernet_profile(&static_ethernet());
        assert_eq!(
            file.destination,
            "/etc/NetworkManager/system-connections/eth0-static.nmconnection"
        );
        assert_eq!(file.mode, "0600");
        assert!(file.contents.contains("type=ethernet"));
        assert!(file.contents.contains("interface-name=eth0"));
        assert!(file.contents.contains("method=manual"));
        assert!(file.contents.contains("address1=192.168.1.50/24,192.168.1.1"));
        assert!(file.contents.contains("dns=192.168.1.1;1.1.1.1;"));
        assert!(file.contents.contains("may-fail=false"));
        assert!(file.contents.contains("autoconnect-priority=100"));
        assert!(!file.sensitive);
    }

    #[test]
    fn uuid_is_stable_and_unique() {
        let a = ethernet_profile(&static_ethernet());
        let b = ethernet_profile(&static_ethernet());
        assert_eq!(a.contents, b.contents);

        let mut other = static_ethernet();
        other.id = "eth0-other".into();
        let c = ethernet_profile(&other);
        let uuid_of =
            |text: &str| text.lines().find(|line| line.starts_with("uuid=")).unwrap().to_string();
        assert_ne!(uuid_of(&a.contents), uuid_of(&c.contents));
    }

    #[test]
    fn dhcp_ethernet_omits_addresses() {
        let mut connection = static_ethernet();
        connection.ip = IpConfig {
            method: IpMethod::Auto,
            address: None,
            gateway: None,
            dns: vec![],
            ignore_auto_dns: false,
            ipv6: IpMethod::Auto,
        };
        let file = ethernet_profile(&connection);
        assert!(file.contents.contains("method=auto"));
        assert!(!file.contents.contains("address1="));
        assert!(file.contents.contains("may-fail=true"));
    }

    #[test]
    fn cloned_mac_is_emitted() {
        let mut connection = static_ethernet();
        connection.mac = Some(MacAddr::parse("02:11:22:33:44:55").unwrap());
        let file = ethernet_profile(&connection);
        assert!(file.contents.contains("cloned-mac-address=02:11:22:33:44:55"));
    }

    fn wifi(security: WifiSecurity, psk: Option<&str>) -> WifiConnection {
        WifiConnection {
            id: "home".into(),
            ssid: "MySSID".into(),
            interface: "wlan0".into(),
            security,
            psk: psk.map(str::to_string),
            hidden: false,
            ip: IpConfig {
                method: IpMethod::Auto,
                address: None,
                gateway: None,
                dns: vec![],
                ignore_auto_dns: false,
                ipv6: IpMethod::Auto,
            },
            autoconnect: true,
            autoconnect_priority: 0,
        }
    }

    #[test]
    fn renders_wpa_psk_wifi() {
        let file = wifi_profile(&wifi(WifiSecurity::WpaPsk, Some("secret-passphrase")));
        assert!(file.contents.contains("type=wifi"));
        assert!(file.contents.contains("ssid=MySSID"));
        assert!(file.contents.contains("key-mgmt=wpa-psk"));
        assert!(file.contents.contains("psk=secret-passphrase"));
        assert!(file.sensitive, "a profile holding a pre-shared key must be marked sensitive");
    }

    #[test]
    fn renders_wpa3_wifi() {
        let file = wifi_profile(&wifi(WifiSecurity::Sae, Some("secret-passphrase")));
        assert!(file.contents.contains("key-mgmt=sae"));
    }

    #[test]
    fn open_wifi_has_no_security_section() {
        let file = wifi_profile(&wifi(WifiSecurity::Open, None));
        assert!(!file.contents.contains("[wifi-security]"));
        assert!(!file.sensitive);
    }

    #[test]
    fn hidden_flag_is_emitted() {
        let mut connection = wifi(WifiSecurity::WpaPsk, Some("secret-passphrase"));
        connection.hidden = true;
        let file = wifi_profile(&connection);
        assert!(file.contents.contains("hidden=true"));
    }

    #[test]
    fn gadget_link_never_becomes_default_route() {
        let gadget = UsbGadget {
            function: rpi_provision_spec::GadgetFunction::Ecm,
            interface: "usb0".into(),
            address: Ipv4Cidr::parse("10.55.0.1/24").unwrap(),
            peer_address: Some(Ipv4Addr::new(10, 55, 0, 2)),
            device_mac: MacAddr::parse("02:11:22:33:44:55").unwrap(),
            host_mac: MacAddr::parse("02:11:22:33:44:56").unwrap(),
            vendor_id: 0x1d6b,
            product_id: 0x0104,
            manufacturer: "Raspberry Pi".into(),
            product: "gadget".into(),
            serial: "pi".into(),
        };
        let file = gadget_profile(&gadget);
        assert!(file.contents.contains("address1=10.55.0.1/24"));
        assert!(file.contents.contains("never-default=true"));
        assert!(file.contents.contains("may-fail=true"));
        assert!(!file.contents.contains("gateway"));
        assert_eq!(
            file.destination,
            "/etc/NetworkManager/system-connections/usb0-gadget.nmconnection"
        );
    }
}
