//! The first-boot runner and its step scripts.
//!
//! The runner is deliberately dumb: it stages the payload into a tmpfs,
//! executes `steps/*.sh` in lexical order, then removes its own hooks from
//! the kernel command line. All decisions were made at render time, so each
//! step is a short, readable, independently testable shell script.

use std::fmt::Write as _;

use rpi_provision_spec::model::SudoMode;
use rpi_provision_spec::Spec;

use crate::gadget;
use crate::Layout;

/// Single-quote a value for safe interpolation into generated shell.
pub fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

const HEADER: &str = "#!/bin/sh";

fn preamble(purpose: &str) -> String {
    format!(
        "{HEADER}\n\
         # Generated by {}. Do not edit.\n\
         # {purpose}\n\
         set -eu\n\
         \n\
         BASE=\"${{RPI_PROVISION_BASE:-/run/rpi-provision}}\"\n\
         \n",
        crate::GENERATOR
    )
}

/// One numbered first-boot step.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Step {
    pub order: u8,
    pub name: &'static str,
    pub body: String,
}

impl Step {
    pub fn file_name(&self) -> String {
        format!("{:02}-{}.sh", self.order, self.name)
    }
}

// ------------------------------------------------------------------- runner

/// The entry point named by `systemd.run=` on the kernel command line.
pub fn firstrun(spec: &Spec, layout: &Layout, digest: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{HEADER}");
    let _ = writeln!(out, "# Generated by {}. Do not edit.", crate::GENERATOR);
    let _ = writeln!(out, "# spec-digest: {digest}");
    let _ = writeln!(out, "#");
    let _ = writeln!(out, "# Run once by systemd through systemd.run= on the kernel command line.");
    let _ = writeln!(out, "# Stages itself into a tmpfs, runs steps/*.sh in order, then removes");
    let _ = writeln!(out, "# its own hooks from cmdline.txt so the next boot is a normal one.");
    let _ = writeln!(out, "set -eu");
    let _ = writeln!(out);
    let _ = writeln!(out, "BOOT_MOUNT={}", quote(&layout.boot_mount));
    let _ = writeln!(out, "BOOT_BASE={}", quote(&layout.runtime_dir));
    let _ = writeln!(out, "STAGE_DIR='/run/rpi-provision'");
    let _ = writeln!(out, "LOG_PATH={}", quote(&spec.provisioning.log_path));
    let _ = writeln!(out, "STATUS_PATH='/var/lib/rpi-provision/status'");
    let _ = writeln!(out, "SPEC_DIGEST={}", quote(digest));
    let _ = writeln!(out, "WIPE_PAYLOAD={}", if spec.provisioning.wipe_payload { 1 } else { 0 });
    let _ = writeln!(out);
    let _ = writeln!(out, "log() {{");
    let _ = writeln!(out, "    printf '[rpi-provision] %s\\n' \"$*\"");
    let _ = writeln!(
        out,
        "    printf '[rpi-provision] %s\\n' \"$*\" >>\"$LOG_PATH\" 2>/dev/null || true"
    );
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "ensure_writable() {{");
    let _ = writeln!(out, "    mount -o remount,rw / 2>/dev/null || true");
    let _ = writeln!(out, "    if ! grep -q \" $BOOT_MOUNT \" /proc/mounts 2>/dev/null; then");
    let _ = writeln!(out, "        mount \"$BOOT_MOUNT\" 2>/dev/null || true");
    let _ = writeln!(out, "    fi");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "# Copy the payload off the FAT partition so that it can be wiped while");
    let _ = writeln!(out, "# this script is still running, and so that secrets live in RAM only.");
    let _ = writeln!(out, "if [ \"${{RPI_PROVISION_STAGED:-0}}\" != \"1\" ]; then");
    let _ = writeln!(out, "    ensure_writable");
    let _ = writeln!(out, "    mkdir -p \"$(dirname \"$LOG_PATH\")\" 2>/dev/null || true");
    let _ = writeln!(out, "    rm -rf \"$STAGE_DIR\"");
    let _ = writeln!(out, "    mkdir -p \"$STAGE_DIR\"");
    let _ = writeln!(out, "    cp -a \"$BOOT_BASE/.\" \"$STAGE_DIR/\"");
    let _ = writeln!(out, "    chmod 0700 \"$STAGE_DIR\"");
    let _ = writeln!(out, "    RPI_PROVISION_STAGED=1");
    let _ = writeln!(out, "    export RPI_PROVISION_STAGED");
    let _ = writeln!(out, "    exec /bin/sh \"$STAGE_DIR/firstrun.sh\" \"$@\"");
    let _ = writeln!(out, "fi");
    let _ = writeln!(out);
    let _ = writeln!(out, "run_steps() {{");
    let _ = writeln!(out, "    for step in \"$STAGE_DIR\"/steps/*.sh; do");
    let _ = writeln!(out, "        [ -e \"$step\" ] || continue");
    let _ = writeln!(out, "        log \"running ${{step##*/}}\"");
    let _ = writeln!(out, "        if ! RPI_PROVISION_BASE=\"$STAGE_DIR\" /bin/sh \"$step\" >>\"$LOG_PATH\" 2>&1; then");
    let _ = writeln!(out, "            log \"step ${{step##*/}} failed\"");
    let _ = writeln!(out, "            tail -n 20 \"$LOG_PATH\" 2>/dev/null || true");
    let _ = writeln!(out, "            return 1");
    let _ = writeln!(out, "        fi");
    let _ = writeln!(out, "    done");
    let _ = writeln!(out, "    return 0");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ =
        writeln!(out, "# Drop the first-boot hooks so a failed run cannot turn into a boot loop.");
    let _ = writeln!(out, "cleanup_cmdline() {{");
    let _ = writeln!(out, "    target=\"$BOOT_MOUNT/cmdline.txt\"");
    let _ = writeln!(out, "    [ -f \"$target\" ] || return 0");
    let _ = writeln!(out, "    sed -i -e 's| *systemd\\.run=[^ ]*||g' \\");
    let _ = writeln!(out, "           -e 's| *systemd\\.run_success_action=[^ ]*||g' \\");
    let _ = writeln!(out, "           -e 's| *systemd\\.unit=[^ ]*||g' \"$target\"");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "ensure_writable");
    let _ = writeln!(out, "log \"starting, spec-digest $SPEC_DIGEST\"");
    let _ = writeln!(out);
    let _ = writeln!(out, "if run_steps; then");
    let _ = writeln!(out, "    STATUS=ok");
    let _ = writeln!(out, "else");
    let _ = writeln!(out, "    STATUS=failed");
    let _ = writeln!(out, "fi");
    let _ = writeln!(out);
    let _ = writeln!(out, "cleanup_cmdline");
    let _ = writeln!(out, "if [ \"$WIPE_PAYLOAD\" = \"1\" ]; then");
    let _ = writeln!(out, "    rm -rf \"$BOOT_BASE\"");
    let _ = writeln!(out, "fi");
    let _ = writeln!(out);
    let _ = writeln!(out, "mkdir -p \"$(dirname \"$STATUS_PATH\")\" 2>/dev/null || true");
    let _ = writeln!(out, "{{");
    let _ = writeln!(out, "    printf 'status=%s\\n' \"$STATUS\"");
    let _ = writeln!(out, "    printf 'digest=%s\\n' \"$SPEC_DIGEST\"");
    let _ = writeln!(out, "    printf 'generator=%s\\n' {}", quote(crate::GENERATOR));
    let _ = writeln!(out, "}} >\"$STATUS_PATH\" 2>/dev/null || true");
    let _ = writeln!(out);
    let _ = writeln!(out, "rm -rf \"$STAGE_DIR\"");
    let _ = writeln!(out, "sync");
    let _ = writeln!(out, "log \"finished with status=$STATUS\"");
    let _ = writeln!(out);
    let _ =
        writeln!(out, "# Always exit successfully: systemd.run_success_action=reboot then takes");
    let _ = writeln!(out, "# the machine into a normal boot, where the log can be inspected.");
    let _ = writeln!(out, "exit 0");
    out
}

// -------------------------------------------------------------------- steps

pub fn hostname_step(spec: &Spec) -> Step {
    let mut out = preamble("Set the host name and keep /etc/hosts consistent.");
    let _ = writeln!(out, "HOSTNAME={}", quote(&spec.system.hostname));
    let _ = writeln!(out);
    let _ = writeln!(out, "printf '%s\\n' \"$HOSTNAME\" >/etc/hostname");
    let _ = writeln!(out, "hostname \"$HOSTNAME\" 2>/dev/null || true");
    let _ = writeln!(out);
    let _ = writeln!(out, "if grep -qE '^127\\.0\\.1\\.1[[:space:]]' /etc/hosts; then");
    let _ = writeln!(
        out,
        "    sed -i \"s|^127\\.0\\.1\\.1[[:space:]].*|127.0.1.1\t$HOSTNAME|\" /etc/hosts"
    );
    let _ = writeln!(out, "else");
    let _ = writeln!(out, "    printf '127.0.1.1\\t%s\\n' \"$HOSTNAME\" >>/etc/hosts");
    let _ = writeln!(out, "fi");
    Step { order: 10, name: "hostname", body: out }
}

pub fn user_step(spec: &Spec, _layout: &Layout) -> Step {
    let user = &spec.user;
    let mut out = preamble("Create the operator account, set its password and group memberships.");
    let _ = writeln!(out, "USER_NAME={}", quote(&user.name));
    let _ = writeln!(out, "USER_SHELL={}", quote(&user.shell));
    let _ = writeln!(out);
    let _ = writeln!(out, "if ! id -u \"$USER_NAME\" >/dev/null 2>&1; then");
    let _ = writeln!(
        out,
        "    useradd --create-home --user-group --shell \"$USER_SHELL\" \"$USER_NAME\""
    );
    let _ = writeln!(out, "fi");
    let _ = writeln!(out, "usermod --shell \"$USER_SHELL\" \"$USER_NAME\"");
    let _ = writeln!(out);

    if user.password_hash.is_some() {
        let _ = writeln!(out, "if [ -f \"$BASE/secrets/password.hash\" ]; then");
        let _ = writeln!(
            out,
            "    printf '%s:%s\\n' \"$USER_NAME\" \"$(cat \"$BASE/secrets/password.hash\")\" \\"
        );
        let _ = writeln!(out, "        | chpasswd --encrypted");
        let _ = writeln!(out, "else");
        let _ = writeln!(out, "    printf 'password hash is missing from the payload\\n' >&2");
        let _ = writeln!(out, "    exit 1");
        let _ = writeln!(out, "fi");
    } else {
        let _ = writeln!(out, "# No password was configured; the account stays locked and is");
        let _ = writeln!(out, "# reachable through its SSH keys only.");
        let _ = writeln!(out, "passwd --lock \"$USER_NAME\" >/dev/null");
    }
    let _ = writeln!(out);

    let mut groups: Vec<String> = user.groups.clone();
    if user.sudo != SudoMode::None && !groups.iter().any(|group| group == "sudo") {
        groups.insert(0, "sudo".to_string());
    }
    if groups.is_empty() {
        let _ = writeln!(out, "# No supplementary groups were requested.");
    } else {
        let quoted: Vec<String> = groups.iter().map(|group| quote(group)).collect();
        let _ = writeln!(out, "for group in {}; do", quoted.join(" "));
        let _ = writeln!(out, "    if getent group \"$group\" >/dev/null 2>&1; then");
        let _ = writeln!(out, "        usermod --append --groups \"$group\" \"$USER_NAME\"");
        let _ = writeln!(out, "    else");
        let _ =
            writeln!(out, "        printf 'group %s does not exist, skipping\\n' \"$group\" >&2");
        let _ = writeln!(out, "    fi");
        let _ = writeln!(out, "done");
    }
    Step { order: 20, name: "user", body: out }
}

/// Install every file listed in `manifest.tsv`.
pub fn payload_step() -> Step {
    let mut out = preamble("Install the generated files onto the root filesystem.");
    let _ = writeln!(out, "MANIFEST=\"$BASE/manifest.tsv\"");
    let _ = writeln!(out, "[ -f \"$MANIFEST\" ] || exit 0");
    let _ = writeln!(out);
    let _ = writeln!(out, "TAB=\"$(printf '\\t')\"");
    let _ = writeln!(out, "while IFS=\"$TAB\" read -r mode source destination; do");
    let _ = writeln!(out, "    case \"$mode\" in");
    let _ = writeln!(out, "        ''|\\#*) continue ;;");
    let _ = writeln!(out, "    esac");
    let _ = writeln!(out, "    [ -n \"$source\" ] && [ -n \"$destination\" ] || continue");
    let _ = writeln!(
        out,
        "    install -D -m \"$mode\" -o root -g root \"$BASE/$source\" \"$destination\""
    );
    let _ = writeln!(out, "    printf 'installed %s (mode %s)\\n' \"$destination\" \"$mode\"");
    let _ = writeln!(out, "    case \"$destination\" in");
    let _ = writeln!(out, "        /etc/sudoers.d/*)");
    let _ = writeln!(out, "            if command -v visudo >/dev/null 2>&1; then");
    let _ = writeln!(out, "                visudo -c -f \"$destination\" >/dev/null");
    let _ = writeln!(out, "            fi");
    let _ = writeln!(out, "            ;;");
    let _ = writeln!(out, "    esac");
    let _ = writeln!(out, "done <\"$MANIFEST\"");
    Step { order: 30, name: "payload", body: out }
}

pub fn ssh_step(spec: &Spec, _layout: &Layout) -> Step {
    let mut out = preamble("Install authorized keys and enable or disable the SSH server.");
    let _ = writeln!(out, "USER_NAME={}", quote(&spec.user.name));
    let _ = writeln!(out);
    if spec.user.authorized_keys.is_empty() {
        let _ = writeln!(out, "# No authorized keys were configured.");
    } else {
        let _ = writeln!(out, "HOME_DIR=\"$(getent passwd \"$USER_NAME\" | cut -d: -f6)\"");
        let _ = writeln!(out, "if [ -z \"$HOME_DIR\" ]; then");
        let _ = writeln!(
            out,
            "    printf 'cannot determine the home directory of %s\\n' \"$USER_NAME\" >&2"
        );
        let _ = writeln!(out, "    exit 1");
        let _ = writeln!(out, "fi");
        let _ = writeln!(out, "USER_GROUP=\"$(id -gn \"$USER_NAME\")\"");
        let _ = writeln!(
            out,
            "install -d -m 0700 -o \"$USER_NAME\" -g \"$USER_GROUP\" \"$HOME_DIR/.ssh\""
        );
        let _ = writeln!(out, "install -m 0600 -o \"$USER_NAME\" -g \"$USER_GROUP\" \\");
        let _ = writeln!(out, "    \"$BASE/authorized_keys\" \"$HOME_DIR/.ssh/authorized_keys\"");
    }
    let _ = writeln!(out);
    if spec.ssh.enabled {
        let _ =
            writeln!(out, "# Validate the configuration before enabling the service. Host keys");
        let _ = writeln!(out, "# may not exist yet on a freshly written card, in which case sshd");
        let _ = writeln!(out, "# cannot self-test and the check is skipped.");
        let _ =
            writeln!(out, "if [ -x /usr/sbin/sshd ] && [ -f /etc/ssh/ssh_host_ed25519_key ]; then");
        let _ = writeln!(out, "    /usr/sbin/sshd -t");
        let _ = writeln!(out, "fi");
        let _ = writeln!(out, "systemctl enable ssh");
    } else {
        let _ = writeln!(out, "systemctl disable ssh 2>/dev/null || true");
        let _ = writeln!(out, "systemctl mask ssh 2>/dev/null || true");
    }
    Step { order: 40, name: "ssh", body: out }
}

pub fn network_step(spec: &Spec) -> Step {
    let mut out = preamble(
        "Tighten permissions on the NetworkManager profiles and set the Wi-Fi regulatory domain.",
    );
    let _ = writeln!(out, "PROFILE_DIR='/etc/NetworkManager/system-connections'");
    let _ = writeln!(out);
    let _ = writeln!(out, "if [ -d \"$PROFILE_DIR\" ]; then");
    let _ = writeln!(out, "    for profile in \"$PROFILE_DIR\"/*.nmconnection; do");
    let _ = writeln!(out, "        [ -e \"$profile\" ] || continue");
    let _ = writeln!(out, "        chown root:root \"$profile\"");
    let _ = writeln!(out, "        chmod 0600 \"$profile\"");
    let _ = writeln!(out, "    done");
    let _ = writeln!(out, "fi");

    if let Some(country) = &spec.network.wifi_country {
        let _ = writeln!(out);
        let _ = writeln!(out, "WIFI_COUNTRY={}", quote(country));
        let _ = writeln!(out, "if command -v raspi-config >/dev/null 2>&1; then");
        let _ = writeln!(out, "    raspi-config nonint do_wifi_country \"$WIFI_COUNTRY\"");
        let _ = writeln!(out, "elif command -v iw >/dev/null 2>&1; then");
        let _ = writeln!(out, "    iw reg set \"$WIFI_COUNTRY\" || true");
        let _ = writeln!(out, "fi");
        let _ = writeln!(out, "if command -v rfkill >/dev/null 2>&1; then");
        let _ = writeln!(out, "    rfkill unblock wifi || true");
        let _ = writeln!(out, "fi");
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "if command -v nmcli >/dev/null 2>&1 \\");
    let _ = writeln!(out, "    && systemctl is-active --quiet NetworkManager 2>/dev/null; then");
    let _ = writeln!(out, "    nmcli connection reload || true");
    let _ = writeln!(out, "fi");
    Step { order: 50, name: "network", body: out }
}

pub fn gadget_step() -> Step {
    let mut out = preamble("Enable the USB gadget unit.");
    let _ = writeln!(out, "systemctl daemon-reload || true");
    let _ = writeln!(out, "systemctl enable {}", gadget::UNIT_NAME);
    Step { order: 60, name: "usb-gadget", body: out }
}

pub fn locale_step(spec: &Spec) -> Step {
    let mut out = preamble("Apply time zone, locale and keyboard settings.");
    let _ = writeln!(out, "if ! command -v raspi-config >/dev/null 2>&1; then");
    let _ = writeln!(out, "    printf 'raspi-config is unavailable, skipping localisation\\n' >&2");
    let _ = writeln!(out, "    exit 0");
    let _ = writeln!(out, "fi");
    let _ = writeln!(out);
    if let Some(timezone) = &spec.system.timezone {
        let _ = writeln!(out, "raspi-config nonint do_change_timezone {}", quote(timezone));
    }
    if let Some(locale) = &spec.system.locale {
        let _ = writeln!(out, "raspi-config nonint do_change_locale {}", quote(locale));
    }
    if let Some(keymap) = &spec.system.keymap {
        let _ = writeln!(out, "raspi-config nonint do_configure_keyboard {}", quote(keymap));
    }
    Step { order: 70, name: "locale", body: out }
}

// ------------------------------------------------------------- sshd config

pub fn sshd_config(spec: &Spec) -> String {
    let mut out = format!("# Generated by {}. Do not edit.\n", crate::GENERATOR);
    let _ = writeln!(out, "Port {}", spec.ssh.port);
    let _ = writeln!(out, "PubkeyAuthentication yes");
    let _ = writeln!(
        out,
        "PasswordAuthentication {}",
        if spec.ssh.password_authentication { "yes" } else { "no" }
    );
    let _ = writeln!(
        out,
        "KbdInteractiveAuthentication {}",
        if spec.ssh.password_authentication { "yes" } else { "no" }
    );
    let _ = writeln!(out, "PermitRootLogin {}", spec.ssh.permit_root_login);
    for line in &spec.ssh.extra_config {
        let _ = writeln!(out, "{line}");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quoting_survives_apostrophes() {
        assert_eq!(quote("plain"), "'plain'");
        assert_eq!(quote("it's"), r"'it'\''s'");
        assert_eq!(quote("$(rm -rf /)"), "'$(rm -rf /)'");
        assert_eq!(quote("a b"), "'a b'");
    }

    #[test]
    fn step_file_names_sort_in_execution_order() {
        let names: Vec<String> = [
            Step { order: 10, name: "hostname", body: String::new() },
            Step { order: 30, name: "payload", body: String::new() },
            Step { order: 70, name: "locale", body: String::new() },
        ]
        .iter()
        .map(Step::file_name)
        .collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted);
        assert_eq!(names[0], "10-hostname.sh");
    }
}
